### PR TITLE
Persister: InventoryCollection building through add_collection()

### PR DESCRIPTION
**Pull request by slemrmartin**
**Issue**: https://github.com/ManageIQ/manageiq/issues/17396
- [x] (**depends on**) PR: https://github.com/ManageIQ/manageiq/pull/17621

New Interface for definition/creating InventoryCollection from persister.
Using add_collection() instead of add_inventory_collection() to build collections.

Builder classes are defined on core project, provider specific InventoryCollections specified in concerns

### CODE REVIEW

**Comment by slemrmartin** [comment]
Cc @agrare, @masayag

**Comment by pkliczewski** [comment]
@slemrmartin Please make sure that the specs are passing.

**Comment by slemrmartin** [comment]
@pkliczewski it should be ok when core PR will be merged, I'll restart tests after it.

**Comment by agrare** [comment]
@pkliczewski can you merge this?  It is holding up cleanup on master

**Comment by pkliczewski** [comment]
@agrare I am sorry for not handling this in timely manner. I was on PTO.

**Comment by agrare** [comment]
@pkliczewski I guess I'll let it slide this time :rofl: hope you had a good time!

**Pull request merged**
