### PR TITLE
Add a rubocop channel to the codeclimate config

### PR DESCRIPTION
**Pull request by djberg96**
Add a rubocop channel to the codeclimate config

### CODE REVIEW

**Comment by agrare** [comment]
@djberg96 any idea why codeclimate is still failing on rubocop-performance?  https://codeclimate.com/github/ManageIQ/manageiq-providers-kubevirt/pull/145

**Comment by djberg96** [comment]
@agrare Are we being mislead? If you click on "view the build" for the link you provided, it takes you to https://codeclimate.com/github/ManageIQ/manageiq-providers-kubevirt/builds/562 which is NOT this build.

This one should be https://codeclimate.com/github/ManageIQ/manageiq-providers-kubevirt/builds/559, which is green.

**Comment by agrare** [comment]
Oh that is weird, codeclimate bug I guess?

**Comment by djberg96** [comment]
@agrare Looks like it to me. I've put in a support request. It's up to you if you want to wait, or just merge it and ignore the failure.

**Comment by agrare** [comment]
No this looks good to me

**Pull request merged**
