### PR TITLE
Removing inventory builder from Refresher

### PR DESCRIPTION
**Pull request by slemrmartin**
Replacing `Inventory::Builder` with Inventory.build instead.

---

**Fixes BZ** https://bugzilla.redhat.com/show_bug.cgi?id=1632131
- [x] together with: #117 
- [x] based on #115

### CODE REVIEW

**Comment by slemrmartin** [comment]
@miq-bot add_label bug
cc @pkliczewski

**Comment by slemrmartin** [comment]
.. @pkliczewski - now I'm waiting for new credentials to test it

**Comment by slemrmartin** [comment]
@pkliczewski tested, it's working

**Comment by pkliczewski** [comment]
@slemrmartin If the change is ready please remove wip flag.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 0b5e14cd1dd72e07c3635ff408fc4a7cea0c2c20
Author: Adam Grare <agrare@redhat.com>
Date:   Tue Oct 23 09:04:16 2018 -0400

    Merge pull request #119 from slemrmartin/missing-inv-builder-refresher
    
    Removing inventory builder from Refresher
    
    (cherry picked from commit 34362614b6c9c40376ecaa22ad57eb99d3febef9)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1632131
```

**Pull request merged**
