### PR TITLE
gemspec: use latest fog-kubevirt

### PR DESCRIPTION
**Pull request by pkliczewski**

### CODE REVIEW

**Comment by pkliczewski** [comment]
@agrare Travis failures seems not to be related to this change. Please take a look.

**Comment by agrare** [comment]
Hey @pkliczewski no it is because of this change, bundler just gives really bad error messages: https://travis-ci.org/ManageIQ/manageiq-providers-kubevirt/jobs/462722048#L620-L627

We'll need to coordinate this with PRs to master and manageiq-providers-kubernetes.

**Comment by pkliczewski** [comment]
@miq-bot added the hammer/yes

**Comment by pkliczewski** [comment]
There are couple of fixes in newer version which needs to be backported

**Comment by pkliczewski** [comment]
@miq-bot add_label hammer/yes

**Comment by pkliczewski** [comment]
This PR fixes https://bugzilla.redhat.com/1660099

**Comment by pkliczewski** [comment]
@miq-bot add_label bug

**Comment by pkliczewski** [comment]
@miq-bot add_label blocker

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit fca04ce5d98d380ca57d24a6724348d5b3d239f8
Author: Gregg Tanzillo <gtanzill@redhat.com>
Date:   Mon Dec 3 16:06:46 2018 -0500

    Merge pull request #125 from pkliczewski/master
    
    gemspec: use latest fog-kubevirt
    (cherry picked from commit 9b94e38db0d8b5567ddc3494bcd30f67cfac45e1)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1660099
```

**Pull request merged**
